"""last_repeat_time = Column(DateTime)

Revision ID: 129a448cc263
Revises: 7a27e41dd1d1
Create Date: 2025-01-01 18:07:05.410870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129a448cc263'
down_revision: Union[str, None] = '7a27e41dd1d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_words', sa.Column('last_repeat_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_words', 'last_repeat_time')
    # ### end Alembic commands ###
