"""with num_of_calls

Revision ID: a9fe36f9ed88
Revises: ed4fbe57b9af
Create Date: 2025-01-05 15:25:25.542659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9fe36f9ed88'
down_revision: Union[str, None] = 'ed4fbe57b9af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
