"""+ field transcription

Revision ID: cdaa94894cd3
Revises: f914281c7aab
Create Date: 2025-01-09 11:26:50.378859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdaa94894cd3'
down_revision: Union[str, None] = 'f914281c7aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('transcription', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'transcription')
    # ### end Alembic commands ###
