"""with num_of_calls

Revision ID: d506556e95aa
Revises: c9f89976cdc4
Create Date: 2025-01-05 14:44:12.188727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd506556e95aa'
down_revision: Union[str, None] = 'c9f89976cdc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('num_of_calls', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'num_of_calls')
    # ### end Alembic commands ###
