"""new structure

Revision ID: e7984c4ba5d0
Revises: 12d896f77e87
Create Date: 2025-01-02 12:56:20.911794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7984c4ba5d0'
down_revision: Union[str, None] = '12d896f77e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_words', sa.Column('correct_answers', sa.Integer(), nullable=True))
    op.add_column('user_words', sa.Column('incorrect_answers', sa.Integer(), nullable=True))
    op.add_column('user_words', sa.Column('current_step', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('words_per_day', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('days_between_lessons', sa.Integer(), nullable=True))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('words', sa.Column('category', sa.String(), nullable=True))
    op.add_column('words', sa.Column('audio_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'audio_path')
    op.drop_column('words', 'category')
    op.alter_column('users', 'telegram_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('users', 'days_between_lessons')
    op.drop_column('users', 'words_per_day')
    op.drop_column('user_words', 'current_step')
    op.drop_column('user_words', 'incorrect_answers')
    op.drop_column('user_words', 'correct_answers')
    # ### end Alembic commands ###
