"""with num_of_calls

Revision ID: ed4fbe57b9af
Revises: d506556e95aa
Create Date: 2025-01-05 14:44:54.126405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed4fbe57b9af'
down_revision: Union[str, None] = 'd506556e95aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('num_of_calls', sa.Integer(), nullable=True))
    op.drop_column('words', 'num_of_calls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('num_of_calls', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'num_of_calls')
    # ### end Alembic commands ###
