"""replace last_repeat_time

Revision ID: f914281c7aab
Revises: 834a89697de1
Create Date: 2025-01-06 12:32:37.405424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f914281c7aab'
down_revision: Union[str, None] = '834a89697de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_words', 'last_repeat_time')
    op.add_column('users', sa.Column('last_repeat_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_repeat_time')
    op.add_column('user_words', sa.Column('last_repeat_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
